name: Test with Bun

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: oven/bun:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run tests
        run: bun test
